--- #YAML:1.0
name:                Tree-SEMETrie
version:             0.04
abstract:            Single-Edge Multi-Edge Trie
license:             perl
author:              
    - Aaron Cohen <aarondcohen@gmail.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::Exception:               0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
